version: 2
project_name: github-pages

builds:
  - skip: true

source:
  enabled: true
  format: "tar.gz"
  name_template: "github-pages-{{ .Version }}"

changelog:
  use: github

release:
  github:
    owner: magichuihui
    name: magichuihui.github.io