version: 2
project_name: github-pages

builds: []  # No Go builds needed

archives:
  - formats: ["tar.gz"]
    meta: true
    name_template: "github-pages-{{ .Version }}"
    files:
      - LICENSE
      - _includes/*
      - _layouts/*
      - _posts/*
      - _assets/*
      - images/*
      - "*.html"
      - "*.yml"
      - CNAME
      - Gemfile


changelog:
  use: github

release:
  github:
    owner: magichuihui
    name: magichuihui.github.io