title: kyra's devops
description: Live to learn, learn to live

url: https://blog.amyinfo.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Blog
      url: /blog
    - title: Contact
      url: /contact

social:
    github: magichuihui
    twitter: magichuihui
    facebook: magichuihui
    email: magichuihui@gmail.com
    linkedin: magichuihui

google_analytics: ""

disqus:
    shortname: magichuihui
