---
version: 3
images:
  base_image:
    name: fedora:40
dependencies:
  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: google.cloud
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.windows
  system:
    - git [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pyOpenSSL
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    # SymLink `python` -> `python3.11`
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3 312
    - RUN echo -e "[google-cloud-cli]\nname=Google Cloud CLI\nbaseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=0\ngpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" > /etc/yum.repos.d/google-cloud-sdk.repo
    - RUN dnf install -y google-cloud-cli && dnf clean all && rm -rf /var/cache/yum
