apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-with-annotations
  labels:
    app: devwebapp-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'devweb-app'
    vault.hashicorp.com/agent-cache-enable: "true"
    vault.hashicorp.com/agent-image: magichuihui/vault:1.17.2
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'kvv2/secret'
    vault.hashicorp.com/secret-volume-path-credentials.txt: '/tmp'
    vault.hashicorp.com/secret-volume-path-delete-pod.sh: "/opt"
    #vault.hashicorp.com/agent-inject-command-credentials.txt: "sh /opt/delete-pod.sh"
    vault.hashicorp.com/template-static-secret-render-interval: "1m"
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: devwebapp2-with-annotations
  labels:
    app: devwebapp2-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'devweb-app2'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/devwebapp/config'
    vault.hashicorp.com/secret-volume-path-credentials.txt: '/tmp'
spec:
  serviceAccountName: internal-app2
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
