apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-with-annotations
  labels:
    app: devwebapp-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'devweb-app'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/devwebapp/config'
    vault.hashicorp.com/secret-volume-path-credentials.txt: '/tmp'
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: devwebapp2-with-annotations
  labels:
    app: devwebapp2-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'devweb-app2'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/devwebapp/config'
    vault.hashicorp.com/secret-volume-path-credentials.txt: '/tmp'
spec:
  serviceAccountName: internal-app2
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
