---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  namespace: default
  name: vault-auth-global
spec:
  defaultAuthMethod: kubernetes
  allowedNamespaces:
  - tenant-1
  kubernetes:
    audiences:
    - vault
    mount: kubernetes
    namespace: default
    role: demo
    serviceAccount: token-reviewer
    tokenExpirationSeconds: 600