apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-reviewer
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-abcde1
  namespace: default
  annotations:
    kubernetes.io/service-account.name: token-reviewer
type: kubernetes.io/service-account-token