apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: tenant-1
  annotations:
    secret.reloader.stakater.com/reload: "secret2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-test
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi          
      volumes:
      - name: secrets
        secret:
          secretName: secret2
          optional: false