name: Generate Release with PR Changelog

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "$GITHUB_REF_NAME" \
            --generate-notes \
            --repo "$GITHUB_REPOSITORY"
