name: Generate Release with PR Changelog

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes with GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REPO: ${{ github.repository }}
        run: |
          NOTES=$(gh api repos/$REPO/releases/generate-notes -f tag_name="$TAG_NAME" | jq -r .body)
          gh release edit "$TAG_NAME" --notes "$NOTES" --repo "$REPO"
